# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import train_pb2 as train__pb2


class TrainTicketStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PurchaseTicket = channel.unary_unary(
                '/TrainTicket/PurchaseTicket',
                request_serializer=train__pb2.TicketRequest.SerializeToString,
                response_deserializer=train__pb2.TicketResponse.FromString,
                )
        self.GetReceiptDetails = channel.unary_unary(
                '/TrainTicket/GetReceiptDetails',
                request_serializer=train__pb2.ReceiptDetailsRequest.SerializeToString,
                response_deserializer=train__pb2.ReceiptDetailsResponse.FromString,
                )
        self.GetUserSeats = channel.unary_unary(
                '/TrainTicket/GetUserSeats',
                request_serializer=train__pb2.UserSeatsRequest.SerializeToString,
                response_deserializer=train__pb2.UserSeatsResponse.FromString,
                )
        self.RemoveUser = channel.unary_unary(
                '/TrainTicket/RemoveUser',
                request_serializer=train__pb2.RemoveUserRequest.SerializeToString,
                response_deserializer=train__pb2.RemoveUserResponse.FromString,
                )
        self.ModifyUserSeat = channel.unary_unary(
                '/TrainTicket/ModifyUserSeat',
                request_serializer=train__pb2.ModifyUserSeatRequest.SerializeToString,
                response_deserializer=train__pb2.ModifyUserSeatResponse.FromString,
                )


class TrainTicketServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PurchaseTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReceiptDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserSeats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyUserSeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainTicketServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PurchaseTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.PurchaseTicket,
                    request_deserializer=train__pb2.TicketRequest.FromString,
                    response_serializer=train__pb2.TicketResponse.SerializeToString,
            ),
            'GetReceiptDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReceiptDetails,
                    request_deserializer=train__pb2.ReceiptDetailsRequest.FromString,
                    response_serializer=train__pb2.ReceiptDetailsResponse.SerializeToString,
            ),
            'GetUserSeats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserSeats,
                    request_deserializer=train__pb2.UserSeatsRequest.FromString,
                    response_serializer=train__pb2.UserSeatsResponse.SerializeToString,
            ),
            'RemoveUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveUser,
                    request_deserializer=train__pb2.RemoveUserRequest.FromString,
                    response_serializer=train__pb2.RemoveUserResponse.SerializeToString,
            ),
            'ModifyUserSeat': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyUserSeat,
                    request_deserializer=train__pb2.ModifyUserSeatRequest.FromString,
                    response_serializer=train__pb2.ModifyUserSeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TrainTicket', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TrainTicket(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PurchaseTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TrainTicket/PurchaseTicket',
            train__pb2.TicketRequest.SerializeToString,
            train__pb2.TicketResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReceiptDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TrainTicket/GetReceiptDetails',
            train__pb2.ReceiptDetailsRequest.SerializeToString,
            train__pb2.ReceiptDetailsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserSeats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TrainTicket/GetUserSeats',
            train__pb2.UserSeatsRequest.SerializeToString,
            train__pb2.UserSeatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TrainTicket/RemoveUser',
            train__pb2.RemoveUserRequest.SerializeToString,
            train__pb2.RemoveUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ModifyUserSeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TrainTicket/ModifyUserSeat',
            train__pb2.ModifyUserSeatRequest.SerializeToString,
            train__pb2.ModifyUserSeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
