# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: train.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btrain.proto\"s\n\rTicketRequest\x12\x11\n\tdeparture\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\x12\x17\n\x0fuser_first_name\x18\x03 \x01(\t\x12\x16\n\x0euser_last_name\x18\x04 \x01(\t\x12\x12\n\nuser_email\x18\x05 \x01(\t\"!\n\x0eTicketResponse\x12\x0f\n\x07receipt\x18\x01 \x01(\t\"(\n\x15ReceiptDetailsRequest\x12\x0f\n\x07receipt\x18\x01 \x01(\t\")\n\x16ReceiptDetailsResponse\x12\x0f\n\x07\x64\x65tails\x18\x01 \x01(\t\"#\n\x10UserSeatsRequest\x12\x0f\n\x07section\x18\x01 \x01(\t\"2\n\x11UserSeatsResponse\x12\x1d\n\nuser_seats\x18\x01 \x03(\x0b\x32\t.UserSeat\"\'\n\x11RemoveUserRequest\x12\x12\n\nuser_email\x18\x01 \x01(\t\"%\n\x12RemoveUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"@\n\x15ModifyUserSeatRequest\x12\x12\n\nuser_email\x18\x01 \x01(\t\x12\x13\n\x0bnew_section\x18\x02 \x01(\t\")\n\x16ModifyUserSeatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"=\n\x08UserSeat\x12\x12\n\nuser_email\x18\x01 \x01(\t\x12\x0f\n\x07section\x18\x02 \x01(\t\x12\x0c\n\x04seat\x18\x03 \x01(\t2\xb7\x02\n\x0bTrainTicket\x12\x31\n\x0ePurchaseTicket\x12\x0e.TicketRequest\x1a\x0f.TicketResponse\x12\x44\n\x11GetReceiptDetails\x12\x16.ReceiptDetailsRequest\x1a\x17.ReceiptDetailsResponse\x12\x35\n\x0cGetUserSeats\x12\x11.UserSeatsRequest\x1a\x12.UserSeatsResponse\x12\x35\n\nRemoveUser\x12\x12.RemoveUserRequest\x1a\x13.RemoveUserResponse\x12\x41\n\x0eModifyUserSeat\x12\x16.ModifyUserSeatRequest\x1a\x17.ModifyUserSeatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'train_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TICKETREQUEST']._serialized_start=15
  _globals['_TICKETREQUEST']._serialized_end=130
  _globals['_TICKETRESPONSE']._serialized_start=132
  _globals['_TICKETRESPONSE']._serialized_end=165
  _globals['_RECEIPTDETAILSREQUEST']._serialized_start=167
  _globals['_RECEIPTDETAILSREQUEST']._serialized_end=207
  _globals['_RECEIPTDETAILSRESPONSE']._serialized_start=209
  _globals['_RECEIPTDETAILSRESPONSE']._serialized_end=250
  _globals['_USERSEATSREQUEST']._serialized_start=252
  _globals['_USERSEATSREQUEST']._serialized_end=287
  _globals['_USERSEATSRESPONSE']._serialized_start=289
  _globals['_USERSEATSRESPONSE']._serialized_end=339
  _globals['_REMOVEUSERREQUEST']._serialized_start=341
  _globals['_REMOVEUSERREQUEST']._serialized_end=380
  _globals['_REMOVEUSERRESPONSE']._serialized_start=382
  _globals['_REMOVEUSERRESPONSE']._serialized_end=419
  _globals['_MODIFYUSERSEATREQUEST']._serialized_start=421
  _globals['_MODIFYUSERSEATREQUEST']._serialized_end=485
  _globals['_MODIFYUSERSEATRESPONSE']._serialized_start=487
  _globals['_MODIFYUSERSEATRESPONSE']._serialized_end=528
  _globals['_USERSEAT']._serialized_start=530
  _globals['_USERSEAT']._serialized_end=591
  _globals['_TRAINTICKET']._serialized_start=594
  _globals['_TRAINTICKET']._serialized_end=905
# @@protoc_insertion_point(module_scope)
